name: Build and attest Python Fibonacci Sequence artifact

on:
  workflow_dispatch:

jobs:
  build:
    name: build package
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.x"

      - name: Build artifact
        run: tar -czf pyfib.tar.gz ./pyfib

      - name: Attest build provenance
        uses: actions/attest-build-provenance@96278af6caaf10aea03fd8d33a09a777ca52d62f # v3.2.0
        with:
          subject-path: "pyfib.tar.gz"

      - name: Upload build artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          path: "pyfib.tar.gz"

      - name: Verify build artifact
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh attestation verify pyfib.tar.gz --owner "$GITHUB_REPOSITORY_OWNER"
